apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/HornetRatHead/goit-argo.git
    targetRevision: main
    path: mlflow
    helm:
      version: v3
      values: |
        global:
          security:
            allowInsecureImages: true

        service:
          type: ClusterIP
          port: 5000

        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: "latest"
          primary:
            persistence:
              enabled: false
          auth:
            postgresPassword: mlflowpass

        minio:
          image:
            repository: minio/minio
            tag: "latest"
          args: ["minio", "server", "/data", "--console-address", ":9001"]
          auth:
            rootUser: "minioadmin"
            rootPassword: "minioadmin"
          persistence:
            enabled: false

        tracking:
          image:
            tag: "latest"
          persistence:
            enabled: false

        backend:
          image:
            tag: "latest"

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

