apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/HornetRatHead/goit-argo.git
    targetRevision: main
    path: mlflow
    helm:
      version: v3
      values: |
        global:
          security:
            allowInsecureImages: true
        service:
          type: ClusterIP
          port: 5000
        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: latest
          primary:
            persistence:
              enabled: false
          auth:
            postgresPassword: mlflowpass
        minio:
          enabled: true
          image:
            registry: docker.io
            repository: minio/minio
            tag: "RELEASE.2025-10-15T17-29-55Z"
          persistence:
            enabled: false
          command: ["minio", "server", "/data", "--console-address", ":9001"]
          auth:
            rootUser: "minioadmin"
            rootPassword: "minioadmin"
        tracking:
          image:
            repository: ghcr.io/mlflow/mlflow
            tag: "v2.15.1"
          persistence:
            enabled: false
        backend:
          image:
            tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

